import Head from 'next/head';
import Image from 'next/image';
import React, { useState, useEffect } from 'react';

export default function Home() {
  const [mode, setMode] = useState('light');

  const handleMode = () => {
    setMode(mode === 'light' ? 'dark' : 'light');
  };

  useEffect(() => {
    document.documentElement.className = mode;
  }, [mode]);

  return (
    <div>
      <Head>
        <title>now!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/Type=dark-mode-picker.svg' />
        <link
          href='https://api.fontshare.com/v2/css?f[]=clash-display@200,400,700,500,600,300&display=swap'
          rel='stylesheet'
        />
      </Head>

      <nav>Hello navbar</nav>

      <main className='bg-green-600 dark:bg-yellow-600'>
        <h1>Hello main</h1>
        <button
          onClick={handleMode}
          className='p-2 bg-red-600 text-white opacity-90 hover:opacity-100'
        >
          Click me
        </button>
      </main>

      <footer>Hello footer</footer>
    </div>
  );
}
